name: web_scraper_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pip
  - python-dotenv
  - pip:
    - numpy==1.22.3
    - pillow==9.1.0
    - pandas==1.4.2
    - openpyxl # required only for local execution of batch_create_user.ipynb
    - beautifulsoup4
    - ipykernel
    - requests